language: java
jdk:
- oraclejdk11
- openjdk11
env:
  global:
  - secure: Zy6jPRwLxe0QtJyPpukaPHRG8j+C1YCQ4ImA8nOpeTx46TRmW5pAf1S4iA34jf+W+Gtp2hZwnr1VG2lTe9vPrL6YvVxnZ9UlPHl2KyulWovn01pDmSbUZ8OYu7fhQz9sbddypBpsHlk57uwaA6lrMnF3hw0uAPMhSzKygIKUH7nZ+sVPofTAVl12YtWUzepCx4i9ClIHeoMzGPVNvlnCHiys8Ape/foa0GPAYo+NAdEQXeDij08gdvzFqUgT2fsjkCKM+xIoPbHOO1cqhRELz/oxOJWKq/RZ+WNTlnrkRAne0qm+KOjBRR5HknUmIGYeG+rkBqiNoSYDdOummEqhviCcb0JohXxclqIn0nwGCQgwoneAfEDOhtrSUCsw9AUrTa8HJrxPieXqPBoMn62SKv3iFXhq/LBKicYqcCrhBMLWrM3YUDtIrqPQY9sLd69UjHABmoaQdBeBuVYGc9Lnn813Y81SUERucCw9Jxm+r+XeW30woZiuVi4LUQC+OjTWzsd1XMCmyC56xXXIs7SnrslnLzobEp8mkiW+uFllWqxbNHx6tvQ/gq74iu4hWHqT4wGF8Zu1ddGw5NiuCf2DuquoS+GuO9Wfq+Zy9K7VyjHFnz+coeqdW+nvtBfr7h0JedC0cz09QDdETxjnf6qJNtvBAZrJO/XflvCfh7GFqI0=
addons:
  sonarcloud:
    organization: bacta
    token:
      secure: "$SONAR_TOKEN"
script:
- "./mvn clean install -B"
- "./mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar"
notifications:
  slack:
    secure: iTdpFnwHGwGbHNS1jnpbaY0m+JCWLILLVLj5YYyYGLprSTKdn7TswQ3rl/dWSTcbl2xf2nq4rYxseyZUcMLhPw7SHeMQCZxgW4B6lQP30MIGa/f6xJxTkyFdYTxnvSG1lMJWVg8cBD7cIStvZ7R3AOt7QY6ADRAW4UKRRXYmi/YUJJiba+lSCLCKjngXfFvr88126RJxAYF5OUiqFaieObEwW+KeGagMMJ/lgv7rFSPHj7zhp5V+osSLiqeTRJYT/34dbCP2UH9Fxo34gF93TvMrlTXQrO013tALdx+cPlhVSiVcl0yoQVSSRRMwLtonU5ny5AFGzJPQp+yTSAx+9hwhQI9owIIL3XvwakRPWvkp4+jOWX9zJkCKug1dbq8tMT+ohAvbVTdnwsHT+/axj3K6/TAAqzry7meY/RRBbfTpiAf7424DB20cQwX+TMR+ARjxjIU+24tDD48UPRMWMPQlCp6zUFBfOf4hxoUB8dXx78pdsJIoxsmVEtNBWeZEO+jElzjQ6KwQdbdNaTeDli75qazIeQFn5tNzEITeHPJjjNCXMrsRW8ejismAgZVO7Pv8ezz5aMdGYvkBlF242p5yj76YWkVfSKxig5/uXzynD1Bt1evJGmpDIw4lOKpg2nmnZ7zAwvlthqnL+nX4bvP1/Bvui7CgKTmHXywzZbY=
