language: java
jdk:
- oraclejdk11
#- openjdk11
env:
  global:
  - secure: Zy6jPRwLxe0QtJyPpukaPHRG8j+C1YCQ4ImA8nOpeTx46TRmW5pAf1S4iA34jf+W+Gtp2hZwnr1VG2lTe9vPrL6YvVxnZ9UlPHl2KyulWovn01pDmSbUZ8OYu7fhQz9sbddypBpsHlk57uwaA6lrMnF3hw0uAPMhSzKygIKUH7nZ+sVPofTAVl12YtWUzepCx4i9ClIHeoMzGPVNvlnCHiys8Ape/foa0GPAYo+NAdEQXeDij08gdvzFqUgT2fsjkCKM+xIoPbHOO1cqhRELz/oxOJWKq/RZ+WNTlnrkRAne0qm+KOjBRR5HknUmIGYeG+rkBqiNoSYDdOummEqhviCcb0JohXxclqIn0nwGCQgwoneAfEDOhtrSUCsw9AUrTa8HJrxPieXqPBoMn62SKv3iFXhq/LBKicYqcCrhBMLWrM3YUDtIrqPQY9sLd69UjHABmoaQdBeBuVYGc9Lnn813Y81SUERucCw9Jxm+r+XeW30woZiuVi4LUQC+OjTWzsd1XMCmyC56xXXIs7SnrslnLzobEp8mkiW+uFllWqxbNHx6tvQ/gq74iu4hWHqT4wGF8Zu1ddGw5NiuCf2DuquoS+GuO9Wfq+Zy9K7VyjHFnz+coeqdW+nvtBfr7h0JedC0cz09QDdETxjnf6qJNtvBAZrJO/XflvCfh7GFqI0=
addons:
  sonarcloud:
    organization: bacta
    token:
      secure: "$SONAR_TOKEN"
script:
- sonar-scanner
notifications:
  slack:
    secure: Omz99q6p96StRYp1ytgyIZZAdeyHuflnwlB/8xTh6Fucb+svc9V0q4dWns4TByOb8HlW/T2Bl7rYt3xKHSt9iI1Bc2Nrh4MnPJJXCRjmOdDtnh4gMXCWn3g/bwZysIEHt/o6QhF3RhZS3aHaC0z+MnE29f2cUrkayB9VPwFArUUrL3B5rMx1OjMEbLS36akvFOr5CEOQjdAmAltAeh5oN7qLWiav/fhzobdODv41AkK4k/nkVrwRBm0KVemz0q+NJXULMBNVp5QX3tgO4yyRjeTaDL1kHxfZH/QAKNmjWKR0QVUpphfSIyVgAJAvREb330LmXqEQecg+uZrJARacZECr1c3w3BRRE4vQfQif6B8T326P2tmndPzSx+bgzRHCsvtZ3NH/lpOrKekOBhvM8tauc3uUTO6EPYjpRQSrUKhTVKXI8U8OqVnxs8wV/2aMzZVwCreb75MJCnmLU38F+WZr7Kz1i2ytLvikybQVX7zdmV56HOpIyZCXHmAtdeSoh3GGgeVy+gRUYhBK/Ux9K28bsWxzst/O7KNqZ1+Rq5ghn0zz5CTuYazEo0l54LqlXqQUinwuxANgfwXsNlj46vZvWE3NeXcuqqYeh+5ycxm6gipu5pOtHoWsh/t3Lz/x1sYvryPdHRqQI4mxfIMxwdQsdSL0aFonU4tbMoYNQlI=
