#
# Copyright 2017. Bacta
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software
# and associated documentation files (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge, publish, distribute,
# sublicense, and/or sell copies of the Software, and to permit persons to whom the Software
# is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or
# substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
spring:
  jmx:
    default-domain: agentservice

endpoints:
  jmx:
    domain: agentservice
    unique-names: true

io:
  bacta:
    game:
      bindAddress: "0.0.0.0"
      bindPort: 44463
      bindPingPort: 44464
      galaxyName: "Bacta"
      requiredClientVersion: "20100225-17:43"


      # Configures the TreeFile archive. See io.bacta.swg.tre for more detailed information.
      # Types of data search nodes:
      # - toc - Table of contents archive. Requires a path and priority.
      # - tree - Tree archive. Requires a path and priority.
      # - path - Path to search. Requires a path and priority.
      # - cache - Not implemented. Requires a priority.
      # - absolute - Enable searching from application path. Requires a priority.
      #
      # Priority determines in what order the search node will be searched. The higher, the better. Multiple
      # nodes can share the same priority in which case they will be searched in the order they are listed.
      #
      # Warning: Placing the server side files in the client directory can cause the client to crash and
      #          is not advised. Recommended to put them in a different directory, and configure tree file
      #          to search for them there below.
      treeFile:
        search:
          - type: "toc"
            path: "swg-client/sku0_client.toc"
            priority: 3

          - type: "toc"
            path: "swg-client/sku1_client.toc"
            priority: 3

          - type: "toc"
            path: "swg-client/sku2_client.toc"
            priority: 3

          - type: "toc"
            path: "swg-client/sku3_client.toc"
            priority: 3

          - type: "path"
            path: "data/sku.0/sys.shared/compiled/game"
            priority: 2

          - type: "path"
            path: "data/sku.0/sys.server/compiled/game"
            priority: 2

          - type: "path"
            path: "data/sku.0/sys.shared/built/game"
            priority: 1

          - type: "path"
            path: "data/sku.0/sys.server/built/game"
            priority: 1

          - type: "absolute"
            priority: 0

      # Deprecating the use of the client directory as the data source for server files.
      clientPath: "swg-client"
      clientIniFile: "live.cfg"

      login:
        rest:
          base:
            "http://localhost:8080/api"
      akka:
        config: "game.conf"
      zoneServers:
          - name: "tatooine"
            iffPath: "/some/iff/path/tatooine"
          - name: "naboo"
            iffPath: "/some/iff/path/naboo"
          - name: "yavin"
            iffPath: "/some/iff/path/yavin"
logging:
  file: logs/game.log
  level:
    org:
      springframework: INFO
    com:
      typesafe:
        akka: INFO
    akka: INFO